name: brawl
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Nico Hämäläinen <nico@sizeof.io>
homepage: http://sizeof.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  events: any
  polymer:
    git:
      url: git://github.com/dart-lang/polymer-dart.git
      ref: behaviors
  web_components: any
  reflectable: any
  cryptoutils: any

transformers:
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.dart

dev_dependencies:
  guinness: '>=0.1.17'
  faker: '>=0.0.2'
